In [20]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df=pd.read_csv(r'C:\Users\Lenovo\Downloads\Compressed\heart_disease_uci.csv')

In [3]:
df.columns

Index(['id', 'age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs',
       'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')

In [4]:
df.shape

(920, 16)

In [5]:
df.head(5)

id  age     sex    dataset               cp  trestbps   chol    fbs  \
0   1   63    Male  Cleveland   typical angina     145.0  233.0   True   
1   2   67    Male  Cleveland     asymptomatic     160.0  286.0  False   
2   3   67    Male  Cleveland     asymptomatic     120.0  229.0  False   
3   4   37    Male  Cleveland      non-anginal     130.0  250.0  False   
4   5   41  Female  Cleveland  atypical angina     130.0  204.0  False   

          restecg  thalch  exang  oldpeak        slope   ca  \
0  lv hypertrophy   150.0  False      2.3  downsloping  0.0   
1  lv hypertrophy   108.0   True      1.5         flat  3.0   
2  lv hypertrophy   129.0   True      2.6         flat  2.0   
3          normal   187.0  False      3.5  downsloping  0.0   
4  lv hypertrophy   172.0  False      1.4    upsloping  0.0   

                thal  num  
0       fixed defect    0  
1             normal    2  
2  reversable defect    1  
3             normal    0  
4             normal    0

In [6]:
df.info

<bound method DataFrame.info of       id  age     sex        dataset               cp  trestbps   chol    fbs  \
0      1   63    Male      Cleveland   typical angina     145.0  233.0   True   
1      2   67    Male      Cleveland     asymptomatic     160.0  286.0  False   
2      3   67    Male      Cleveland     asymptomatic     120.0  229.0  False   
3      4   37    Male      Cleveland      non-anginal     130.0  250.0  False   
4      5   41  Female      Cleveland  atypical angina     130.0  204.0  False   
..   ...  ...     ...            ...              ...       ...    ...    ...   
915  916   54  Female  VA Long Beach     asymptomatic     127.0  333.0   True   
916  917   62    Male  VA Long Beach   typical angina       NaN  139.0  False   
917  918   55    Male  VA Long Beach     asymptomatic     122.0  223.0   True   
918  919   58    Male  VA Long Beach     asymptomatic       NaN  385.0   True   
919  920   62    Male  VA Long Beach  atypical angina     120.0  254.0  False

In [7]:
df.describe

<bound method NDFrame.describe of       id  age     sex        dataset               cp  trestbps   chol    fbs  \
0      1   63    Male      Cleveland   typical angina     145.0  233.0   True   
1      2   67    Male      Cleveland     asymptomatic     160.0  286.0  False   
2      3   67    Male      Cleveland     asymptomatic     120.0  229.0  False   
3      4   37    Male      Cleveland      non-anginal     130.0  250.0  False   
4      5   41  Female      Cleveland  atypical angina     130.0  204.0  False   
..   ...  ...     ...            ...              ...       ...    ...    ...   
915  916   54  Female  VA Long Beach     asymptomatic     127.0  333.0   True   
916  917   62    Male  VA Long Beach   typical angina       NaN  139.0  False   
917  918   55    Male  VA Long Beach     asymptomatic     122.0  223.0   True   
918  919   58    Male  VA Long Beach     asymptomatic       NaN  385.0   True   
919  920   62    Male  VA Long Beach  atypical angina     120.0  254.0  Fal

In [8]:
df.isnull().sum()

id            0
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [9]:
numerical_features = df.select_dtypes(include=[np.number]).columns.tolist()
numerical_features

['id', 'age', 'trestbps', 'chol', 'thalch', 'oldpeak', 'ca', 'num']

In [10]:
df = df.drop(columns=["ca"])
df.head()

id  age     sex    dataset               cp  trestbps   chol    fbs  \
0   1   63    Male  Cleveland   typical angina     145.0  233.0   True   
1   2   67    Male  Cleveland     asymptomatic     160.0  286.0  False   
2   3   67    Male  Cleveland     asymptomatic     120.0  229.0  False   
3   4   37    Male  Cleveland      non-anginal     130.0  250.0  False   
4   5   41  Female  Cleveland  atypical angina     130.0  204.0  False   

          restecg  thalch  exang  oldpeak        slope               thal  num  
0  lv hypertrophy   150.0  False      2.3  downsloping       fixed defect    0  
1  lv hypertrophy   108.0   True      1.5         flat             normal    2  
2  lv hypertrophy   129.0   True      2.6         flat  reversable defect    1  
3          normal   187.0  False      3.5  downsloping             normal    0  
4  lv hypertrophy   172.0  False      1.4    upsloping             normal    0

In [15]:
df['trestbps']=df["trestbps"].fillna(df["trestbps"].median())
df["chol"]=df["chol"].fillna(df["chol"].median())
df["fbs"]=df["fbs"].fillna(df["fbs"].mode()[0])
df["restecg"]=df["restecg"].fillna(df["restecg"].mode()[0])
df["thalch"]=df["thalch"].fillna(df["thalch"].median())
df["exang"]=df["exang"].fillna(df["exang"].mode()[0])
df["oldpeak"]=df["oldpeak"].fillna(df["oldpeak"].median())
df["slope"]=df["slope"].fillna(df["slope"].mode()[0])
df["thal"]=df["thal"].fillna(df["thal"].mode()[0])
df.isnull().sum()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11436\1240138564.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["fbs"]=df["fbs"].fillna(df["fbs"].mode()[0])
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11436\1240138564.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["exang"]=df["exang"].fillna(df["exang"].mode()[0])


id          0
age         0
sex         0
dataset     0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalch      0
exang       0
oldpeak     0
slope       0
thal        0
num         0
dtype: int64

In [16]:
X = df.drop(["num"], axis=1)
y = df["num"]


In [17]:
X

id  age     sex        dataset               cp  trestbps   chol    fbs  \
0      1   63    Male      Cleveland   typical angina     145.0  233.0   True   
1      2   67    Male      Cleveland     asymptomatic     160.0  286.0  False   
2      3   67    Male      Cleveland     asymptomatic     120.0  229.0  False   
3      4   37    Male      Cleveland      non-anginal     130.0  250.0  False   
4      5   41  Female      Cleveland  atypical angina     130.0  204.0  False   
..   ...  ...     ...            ...              ...       ...    ...    ...   
915  916   54  Female  VA Long Beach     asymptomatic     127.0  333.0   True   
916  917   62    Male  VA Long Beach   typical angina     130.0  139.0  False   
917  918   55    Male  VA Long Beach     asymptomatic     122.0  223.0   True   
918  919   58    Male  VA Long Beach     asymptomatic     130.0  385.0   True   
919  920   62    Male  VA Long Beach  atypical angina     120.0  254.0  False   

              restecg  thalch  exang  oldpeak        slope               thal  
0      lv hypertrophy   150.0  False      2.3  downsloping       fixed defect  
1      lv hypertrophy   108.0   True      1.5         flat             normal  
2      lv hypertrophy   129.0   True      2.6         flat  reversable defect  
3              normal   187.0  False      3.5  downsloping             normal  
4      lv hypertrophy   172.0  False      1.4    upsloping             normal  
..                ...     ...    ...      ...          ...                ...  
915  st-t abnormality   154.0  False      0.0         flat             normal  
916  st-t abnormality   140.0  False      0.5         flat             normal  
917  st-t abnormality   100.0  False      0.0         flat       fixed defect  
918    lv hypertrophy   140.0  False      0.5         flat             normal  
919    lv hypertrophy    93.0   True      0.0         flat             normal  

[920 rows x 14 columns]

In [18]:
y

0      0
1      2
2      1
3      0
4      0
      ..
915    1
916    0
917    2
918    0
919    1
Name: num, Length: 920, dtype: int64

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

categorical_features = ["sex", "dataset", "cp", "restecg", "exang", "slope", "thal"]

numerical_features = ["age", "trestbps", "chol", "fbs", "thalch", "oldpeak"]

X_train_num = X_train[numerical_features]

X_test_num = X_test[numerical_features]

scaler = StandardScaler()

X_train_num_scaled = scaler.fit_transform(X_train_num)

X_test_num_scaled = scaler.fit_transform(X_test_num)

oht = OneHotEncoder(sparse_output=False, drop="first")

X_train_cat = X_train[categorical_features]

X_test_cat = X_test[categorical_features]

In [25]:
X_train_cat_encoded = oht.fit_transform(X_train_cat)

X_test_cat_encoded = oht.transform(X_test_cat)

X_train_transformed = np.hstack((X_train_num_scaled, X_train_cat_encoded)) #hstack==>yatay birleştirme

X_test_transformed = np.hstack((X_test_num_scaled, X_test_cat_encoded))

rf = RandomForestClassifier(n_estimators=100, random_state=42)

knn = KNeighborsClassifier()

voting_clf=VotingClassifier(estimators=[("rf", rf),("knn", knn)], voting="soft")

voting_clf.fit(X_train_transformed, y_train)

y_pred = voting_clf.predict(X_test_transformed)

print("Accuracy: ", accuracy_score(y_test, y_pred))

print("Confusion Matrix: ")

cm = confusion_matrix(y_test, y_pred)

print(cm)

print("Classification Report:")

print(classification_report(y_test, y_pred))


Accuracy:  0.5760869565217391
Confusion Matrix: 
[[66  7  1  0  1]
 [17 28  6  2  1]
 [ 3  9  7  6  0]
 [ 7 11  2  5  1]
 [ 0  0  1  3  0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.88      0.79        75
           1       0.51      0.52      0.51        54
           2       0.41      0.28      0.33        25
           3       0.31      0.19      0.24        26
           4       0.00      0.00      0.00         4

    accuracy                           0.58       184
   macro avg       0.39      0.37      0.37       184
weighted avg       0.54      0.58      0.55       184

